---
title: "Resume"
---

## EDUCATION

### Columbia University Mailman School of Public Health, New York, NY

Master of Science, Biostatistics/Pharmaceutical Statistics Track

Relevant coursework: Data Science, Biostatistical Methods, Pharmaceutical Statistics, Statistical Computing in SAS (Spring 2019), Relational Databases and SQL programming for Research and Data Science (Spring 2019), Bayesian Analysis and Adaptive Designs in Clinical Trials (Spring 2019)

### Sun Yat-sen University (SYSU), Guangzhou, China

Bachelor of Medicine (5-year program), Preventive Medicine

Relevant coursework: Medical Statistics, Pharmacology, Genetics, Epidemiology

Thesis: Association Between Spicy Foods Intake and Lipid Profile in Older Chinese

## RESEARCH EXPERIENCE

### Association Between Spicy Foods Intake and Lipid Profile in Older Chinese, China 

• Extracted baseline data from Guangzhou Biobank Study with 30,325 records; conducted logistic regression and multivariate linear regression to analyze the association of spicy food intake and serum lipid profiles in STATA

• Recipient of Outstanding Dissertation

### Estimation of Nepali Children’s Health Status and Analysis of Influencing Factors, China

• Assisted project by extracting useful data from demographic health surveys into STATA

• Explored spatial and temporal distribution with linear model and basic Bayesian analysis in R

### Research into Operational Status and Development Mode of Internet Hospital, China

• Headed to 30 consulting points at the pharmacy in 5 districts for data collection; interviewed patients with self-designed questionnaires; analyzed customer data with R and produced readable reports

• Brought forward implemented suggestion for Internet Hospital to more scientific distribute consulting points; won the Grand Prize of the National Challenge Cup Competition

### University of Lausanne Summer Undergraduate Research Program, Switzerland 

• Collaborated with 5 colleagues on the team for experiment of immune response; gave presentation at final symposium

• Successfully became one of the 25 members from across the world to win entrance to program and full scholarships

## VOLUNTEER LEADERSHIP

### Guangzhou Marathon Medical Volunteer

### Teaching Assistance of the NGO Group Gapper at Bali Island

### Team Leader of 100 Plus People in SYSU Youth Volunteer Association
